services:
  mongodb:
    image: mongo:7
    container_name: datawatch-mongo
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: datawatch

  redis:
    image: redis:7-alpine
    container_name: datawatch-redis
    ports:
      - "6383:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
