package seed

import "github.com/joelee/datawatch/internal/models"

var all = []models.MCCNetwork{models.NetworkVisa, models.NetworkMastercard, models.NetworkUnionPay, models.NetworkAmex, models.NetworkDiscover, models.NetworkDiners, models.NetworkJCB}

// MCCData contains the MCC catalog organized by category.
// Risk levels: high = commonly flagged in AML/compliance, medium = monitor, low = normal commerce.
var MCCData = []models.MCC{
	// ── Aerolineas / Airlines ────────────────────────────────────────
	{Code: "3000", Description: "United Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3001", Description: "American Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3002", Description: "Pan American", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3003", Description: "Eurofly / Meridiana", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3004", Description: "Dragon Air", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3005", Description: "British Airways", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3006", Description: "Japan Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3007", Description: "Air France", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3008", Description: "Lufthansa", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3009", Description: "Air Canada", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3010", Description: "KLM Royal Dutch Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3011", Description: "AeroPeru", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3012", Description: "Qantas", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3013", Description: "Alitalia", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3014", Description: "Saudi Arabian Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3015", Description: "Swiss International Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3016", Description: "SAS Scandinavian Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3017", Description: "South African Airways", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3018", Description: "Varig / GOL Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3020", Description: "Air India", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3021", Description: "Air Algerie", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3023", Description: "TAP Portugal", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3026", Description: "Ryanair", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3031", Description: "Delta Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3032", Description: "TAM Airlines / LATAM", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3033", Description: "Cathay Pacific", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3034", Description: "Korean Air", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3035", Description: "ANA All Nippon Airways", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3036", Description: "Air New Zealand", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3038", Description: "Emirates", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3039", Description: "Avianca", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3044", Description: "Copa Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3045", Description: "Volaris", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3047", Description: "Aeromexico", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3048", Description: "Philippine Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3049", Description: "Turkish Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3050", Description: "Ethiopian Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3051", Description: "Viva Aerobus", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3052", Description: "Spirit Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3053", Description: "Southwest Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3055", Description: "Frontier Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3058", Description: "JetBlue Airways", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3060", Description: "Wingo", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3062", Description: "EasyJet", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3065", Description: "Qatar Airways", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3066", Description: "Etihad Airways", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3068", Description: "Interjet / ABC Aerolineas", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3069", Description: "JetSMART", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3071", Description: "Sky Airline", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3082", Description: "Thai Airways", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3083", Description: "China Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3084", Description: "China Southern Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3085", Description: "China Eastern Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3087", Description: "Vietnam Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3096", Description: "Hawaiian Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3099", Description: "Iberia Airlines", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3174", Description: "Aero Republica (Copa Colombia)", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "3212", Description: "Cubana de Aviacion", Category: "Aerolineas", Networks: all, RiskLevel: "high"},
	{Code: "3246", Description: "TACA / Grupo TACA", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},
	{Code: "4511", Description: "Lineas aereas y transportistas aereos", Category: "Aerolineas", Networks: all, RiskLevel: "medium"},

	// ── Hoteles / Hotels ─────────────────────────────────────────────
	{Code: "3501", Description: "Hilton Hotels", Category: "Hoteles", Networks: all, RiskLevel: "low"},
	{Code: "3502", Description: "Sheraton Hotels", Category: "Hoteles", Networks: all, RiskLevel: "low"},
	{Code: "3503", Description: "Westin Hotels", Category: "Hoteles", Networks: all, RiskLevel: "low"},
	{Code: "3504", Description: "Marriott Hotels", Category: "Hoteles", Networks: all, RiskLevel: "low"},
	{Code: "3505", Description: "Hyatt Hotels", Category: "Hoteles", Networks: all, RiskLevel: "low"},
	{Code: "3506", Description: "Holiday Inn / IHG", Category: "Hoteles", Networks: all, RiskLevel: "low"},
	{Code: "3507", Description: "Radisson Hotels", Category: "Hoteles", Networks: all, RiskLevel: "low"},
	{Code: "3508", Description: "Wyndham Hotels", Category: "Hoteles", Networks: all, RiskLevel: "low"},
	{Code: "3509", Description: "Best Western Hotels", Category: "Hoteles", Networks: all, RiskLevel: "low"},
	{Code: "3510", Description: "Crowne Plaza / IHG", Category: "Hoteles", Networks: all, RiskLevel: "low"},
	{Code: "3512", Description: "Four Seasons Hotels", Category: "Hoteles", Networks: all, RiskLevel: "low"},
	{Code: "3515", Description: "Fairmont Hotels", Category: "Hoteles", Networks: all, RiskLevel: "low"},
	{Code: "3522", Description: "NH Hotels", Category: "Hoteles", Networks: all, RiskLevel: "low"},
	{Code: "3527", Description: "Accor Hotels (Novotel, Ibis)", Category: "Hoteles", Networks: all, RiskLevel: "low"},
	{Code: "3533", Description: "Ritz-Carlton Hotels", Category: "Hoteles", Networks: all, RiskLevel: "low"},
	{Code: "3640", Description: "Cadenas hoteleras varias", Category: "Hoteles", Networks: all, RiskLevel: "low"},
	{Code: "7011", Description: "Hoteles, moteles, resorts", Category: "Hoteles", Networks: all, RiskLevel: "low"},
	{Code: "7012", Description: "Timeshare", Category: "Hoteles", Networks: all, RiskLevel: "medium"},

	// ── Renta de Autos / Car Rental ──────────────────────────────────
	{Code: "3351", Description: "Hertz Rent-A-Car", Category: "Renta de Autos", Networks: all, RiskLevel: "low"},
	{Code: "3352", Description: "Avis Rent-A-Car", Category: "Renta de Autos", Networks: all, RiskLevel: "low"},
	{Code: "3353", Description: "Budget Rent-A-Car", Category: "Renta de Autos", Networks: all, RiskLevel: "low"},
	{Code: "3354", Description: "National Car Rental", Category: "Renta de Autos", Networks: all, RiskLevel: "low"},
	{Code: "3355", Description: "Enterprise Rent-A-Car", Category: "Renta de Autos", Networks: all, RiskLevel: "low"},
	{Code: "3357", Description: "Dollar Rent-A-Car", Category: "Renta de Autos", Networks: all, RiskLevel: "low"},
	{Code: "3359", Description: "Alamo Rent-A-Car", Category: "Renta de Autos", Networks: all, RiskLevel: "low"},
	{Code: "7512", Description: "Agencias de renta de autos", Category: "Renta de Autos", Networks: all, RiskLevel: "low"},

	// ── Casinos y Juegos de Azar / Gambling ──────────────────────────
	{Code: "7800", Description: "Apuestas gubernamentales (loterias)", Category: "Casinos y Juegos", Networks: all, RiskLevel: "high"},
	{Code: "7801", Description: "Apuestas en linea y casas de apuestas (no presencial)", Category: "Casinos y Juegos", Networks: all, RiskLevel: "high"},
	{Code: "7802", Description: "Apuestas en hipodromo y carreras", Category: "Casinos y Juegos", Networks: all, RiskLevel: "high"},
	{Code: "7995", Description: "Casinos, fichas de juego, apuestas", Category: "Casinos y Juegos", Networks: all, RiskLevel: "high"},
	{Code: "7993", Description: "Entretenimiento y videojuegos (no apuestas)", Category: "Casinos y Juegos", Networks: all, RiskLevel: "low"},

	// ── Servicios Financieros / Financial Services ───────────────────
	{Code: "4829", Description: "Giros y transferencias de dinero", Category: "Servicios Financieros", Networks: all, RiskLevel: "high"},
	{Code: "6010", Description: "Instituciones financieras - desembolsos de efectivo", Category: "Servicios Financieros", Networks: all, RiskLevel: "high"},
	{Code: "6011", Description: "Instituciones financieras - retiros en cajeros", Category: "Servicios Financieros", Networks: all, RiskLevel: "medium"},
	{Code: "6012", Description: "Instituciones financieras - productos financieros", Category: "Servicios Financieros", Networks: all, RiskLevel: "medium"},
	{Code: "6050", Description: "Cuasi-efectivo - instituciones financieras", Category: "Servicios Financieros", Networks: all, RiskLevel: "high"},
	{Code: "6051", Description: "Cuasi-efectivo - casas de cambio, criptomonedas", Category: "Servicios Financieros", Networks: all, RiskLevel: "high"},
	{Code: "6211", Description: "Corredores de bolsa y valores", Category: "Servicios Financieros", Networks: all, RiskLevel: "high"},
	{Code: "6300", Description: "Seguros (ventas y suscripcion)", Category: "Servicios Financieros", Networks: all, RiskLevel: "medium"},
	{Code: "6513", Description: "Bienes raices - agentes e inmobiliarias", Category: "Servicios Financieros", Networks: all, RiskLevel: "high"},
	{Code: "6540", Description: "Tarjetas de valor almacenado (gift cards, prepago)", Category: "Servicios Financieros", Networks: all, RiskLevel: "high"},

	// ── Transferencias y Envios / Money Transfer ─────────────────────
	{Code: "4816", Description: "Servicios de computacion en red", Category: "Transferencias", Networks: all, RiskLevel: "high"},

	// ── Joyeria y Metales Preciosos / Jewelry ────────────────────────
	{Code: "5094", Description: "Piedras y metales preciosos al por mayor", Category: "Joyeria y Metales", Networks: all, RiskLevel: "high"},
	{Code: "5944", Description: "Joyerias, relojerias", Category: "Joyeria y Metales", Networks: all, RiskLevel: "high"},

	// ── Casas de Empeno / Pawn Shops ─────────────────────────────────
	{Code: "5933", Description: "Casas de empeno", Category: "Casas de Empeno", Networks: all, RiskLevel: "high"},

	// ── Supermercados y Tiendas / Retail ──────────────────────────────
	{Code: "5300", Description: "Tiendas mayoristas (Costco, Sam's)", Category: "Supermercados", Networks: all, RiskLevel: "low"},
	{Code: "5311", Description: "Tiendas departamentales", Category: "Supermercados", Networks: all, RiskLevel: "low"},
	{Code: "5331", Description: "Tiendas de variedad y descuento", Category: "Supermercados", Networks: all, RiskLevel: "low"},
	{Code: "5399", Description: "Tiendas de mercancias generales", Category: "Supermercados", Networks: all, RiskLevel: "low"},
	{Code: "5411", Description: "Supermercados y abarrotes", Category: "Supermercados", Networks: all, RiskLevel: "low"},
	{Code: "5422", Description: "Carnes y mariscos congelados", Category: "Supermercados", Networks: all, RiskLevel: "low"},
	{Code: "5441", Description: "Dulcerias, confiterias", Category: "Supermercados", Networks: all, RiskLevel: "low"},
	{Code: "5451", Description: "Tiendas de lacteos", Category: "Supermercados", Networks: all, RiskLevel: "low"},
	{Code: "5462", Description: "Panaderias", Category: "Supermercados", Networks: all, RiskLevel: "low"},
	{Code: "5499", Description: "Tiendas miscelaneas de alimentos", Category: "Supermercados", Networks: all, RiskLevel: "low"},
	{Code: "5541", Description: "Gasolineras", Category: "Gasolineras", Networks: all, RiskLevel: "low"},
	{Code: "5542", Description: "Estaciones de combustible automatizadas", Category: "Gasolineras", Networks: all, RiskLevel: "low"},

	// ── Restaurantes / Restaurants ────────────────────────────────────
	{Code: "5812", Description: "Restaurantes", Category: "Restaurantes", Networks: all, RiskLevel: "low"},
	{Code: "5813", Description: "Bares, cantinas, discotecas", Category: "Restaurantes", Networks: all, RiskLevel: "medium"},
	{Code: "5814", Description: "Comida rapida (fast food)", Category: "Restaurantes", Networks: all, RiskLevel: "low"},

	// ── Farmacias y Salud / Health ───────────────────────────────────
	{Code: "5122", Description: "Farmacias y drogas al por mayor", Category: "Farmacia y Salud", Networks: all, RiskLevel: "low"},
	{Code: "5912", Description: "Farmacias y droguerias", Category: "Farmacia y Salud", Networks: all, RiskLevel: "low"},
	{Code: "8011", Description: "Doctores y medicos", Category: "Farmacia y Salud", Networks: all, RiskLevel: "low"},
	{Code: "8021", Description: "Dentistas y ortodoncistas", Category: "Farmacia y Salud", Networks: all, RiskLevel: "low"},
	{Code: "8031", Description: "Osteopatas", Category: "Farmacia y Salud", Networks: all, RiskLevel: "low"},
	{Code: "8041", Description: "Quiropracticos", Category: "Farmacia y Salud", Networks: all, RiskLevel: "low"},
	{Code: "8042", Description: "Opticas y optometras", Category: "Farmacia y Salud", Networks: all, RiskLevel: "low"},
	{Code: "8043", Description: "Oftalmologos", Category: "Farmacia y Salud", Networks: all, RiskLevel: "low"},
	{Code: "8049", Description: "Podologos", Category: "Farmacia y Salud", Networks: all, RiskLevel: "low"},
	{Code: "8050", Description: "Centros de enfermeria y cuidado", Category: "Farmacia y Salud", Networks: all, RiskLevel: "low"},
	{Code: "8062", Description: "Hospitales", Category: "Farmacia y Salud", Networks: all, RiskLevel: "low"},
	{Code: "8071", Description: "Laboratorios medicos y dentales", Category: "Farmacia y Salud", Networks: all, RiskLevel: "low"},
	{Code: "8099", Description: "Servicios medicos varios", Category: "Farmacia y Salud", Networks: all, RiskLevel: "low"},

	// ── Tecnologia y Electronica / Tech ──────────────────────────────
	{Code: "5045", Description: "Equipos perifericos de computo", Category: "Tecnologia", Networks: all, RiskLevel: "low"},
	{Code: "5065", Description: "Partes y equipos electronicos", Category: "Tecnologia", Networks: all, RiskLevel: "low"},
	{Code: "5732", Description: "Tiendas de electronica", Category: "Tecnologia", Networks: all, RiskLevel: "low"},
	{Code: "5734", Description: "Software de computadora", Category: "Tecnologia", Networks: all, RiskLevel: "low"},
	{Code: "5735", Description: "Discos, musica, videojuegos", Category: "Tecnologia", Networks: all, RiskLevel: "low"},
	{Code: "5816", Description: "Juegos digitales / apps", Category: "Tecnologia", Networks: all, RiskLevel: "low"},
	{Code: "5817", Description: "Software de aplicaciones (en linea)", Category: "Tecnologia", Networks: all, RiskLevel: "low"},
	{Code: "5818", Description: "Servicios digitales grandes (marketplace)", Category: "Tecnologia", Networks: all, RiskLevel: "low"},

	// ── E-Commerce y Comercio Digital ─────────────────────────────────
	{Code: "5964", Description: "Venta directa por catalogo", Category: "Comercio Digital", Networks: all, RiskLevel: "medium"},
	{Code: "5965", Description: "Venta directa por catalogo (continuidad)", Category: "Comercio Digital", Networks: all, RiskLevel: "medium"},
	{Code: "5966", Description: "Ventas por catalogo outbound", Category: "Comercio Digital", Networks: all, RiskLevel: "medium"},
	{Code: "5967", Description: "Ventas por catalogo inbound", Category: "Comercio Digital", Networks: all, RiskLevel: "medium"},
	{Code: "5968", Description: "Suscripciones periodicas / continuidad", Category: "Comercio Digital", Networks: all, RiskLevel: "medium"},
	{Code: "5969", Description: "Telemarketing de mercancias", Category: "Comercio Digital", Networks: all, RiskLevel: "medium"},

	// ── Servicios Profesionales / Professional ────────────────────────
	{Code: "7392", Description: "Consultoria administrativa y gerencial", Category: "Servicios Profesionales", Networks: all, RiskLevel: "medium"},
	{Code: "8111", Description: "Servicios legales y abogados", Category: "Servicios Profesionales", Networks: all, RiskLevel: "high"},
	{Code: "8931", Description: "Contadores, auditores, tenedurias", Category: "Servicios Profesionales", Networks: all, RiskLevel: "medium"},
	{Code: "8999", Description: "Servicios profesionales no clasificados", Category: "Servicios Profesionales", Networks: all, RiskLevel: "medium"},

	// ── Transporte / Transportation ──────────────────────────────────
	{Code: "4111", Description: "Transporte local y suburbano (trenes, buses)", Category: "Transporte", Networks: all, RiskLevel: "low"},
	{Code: "4112", Description: "Ferrocarriles de pasajeros", Category: "Transporte", Networks: all, RiskLevel: "low"},
	{Code: "4121", Description: "Taxis y limusinas", Category: "Transporte", Networks: all, RiskLevel: "low"},
	{Code: "4131", Description: "Lineas de autobuses", Category: "Transporte", Networks: all, RiskLevel: "low"},
	{Code: "4214", Description: "Transporte de carga y mudanzas", Category: "Transporte", Networks: all, RiskLevel: "low"},
	{Code: "4411", Description: "Cruceros y lineas maritimas", Category: "Transporte", Networks: all, RiskLevel: "medium"},
	{Code: "4468", Description: "Marinas y embarcaciones", Category: "Transporte", Networks: all, RiskLevel: "medium"},
	{Code: "4722", Description: "Agencias de viaje y operadores turisticos", Category: "Transporte", Networks: all, RiskLevel: "medium"},
	{Code: "4784", Description: "Peajes y cuotas de carretera", Category: "Transporte", Networks: all, RiskLevel: "low"},
	{Code: "4789", Description: "Servicio de transporte no clasificado", Category: "Transporte", Networks: all, RiskLevel: "low"},
	{Code: "7523", Description: "Estacionamientos y garajes", Category: "Transporte", Networks: all, RiskLevel: "low"},

	// ── Telecomunicaciones / Telecom ─────────────────────────────────
	{Code: "4812", Description: "Equipo de telecomunicaciones", Category: "Telecomunicaciones", Networks: all, RiskLevel: "low"},
	{Code: "4813", Description: "Servicio telefonico y larga distancia", Category: "Telecomunicaciones", Networks: all, RiskLevel: "low"},
	{Code: "4814", Description: "Servicio de fax y telecomunicaciones", Category: "Telecomunicaciones", Networks: all, RiskLevel: "low"},
	{Code: "4815", Description: "Servicios de telefonia celular prepago", Category: "Telecomunicaciones", Networks: all, RiskLevel: "medium"},
	{Code: "4816", Description: "Red de computadoras / servicios de informacion", Category: "Telecomunicaciones", Networks: all, RiskLevel: "low"},
	{Code: "4821", Description: "Servicio de telegrafo", Category: "Telecomunicaciones", Networks: all, RiskLevel: "medium"},
	{Code: "4899", Description: "TV por cable, satelital y otros pagos", Category: "Telecomunicaciones", Networks: all, RiskLevel: "low"},

	// ── Servicios Publicos / Utilities ────────────────────────────────
	{Code: "4900", Description: "Servicios electricos, gas, agua, sanitarios", Category: "Servicios Publicos", Networks: all, RiskLevel: "low"},

	// ── Educacion / Education ────────────────────────────────────────
	{Code: "8211", Description: "Escuelas primarias y secundarias", Category: "Educacion", Networks: all, RiskLevel: "low"},
	{Code: "8220", Description: "Universidades y colegios", Category: "Educacion", Networks: all, RiskLevel: "low"},
	{Code: "8241", Description: "Escuelas por correspondencia", Category: "Educacion", Networks: all, RiskLevel: "low"},
	{Code: "8244", Description: "Escuelas comerciales / de negocios", Category: "Educacion", Networks: all, RiskLevel: "low"},
	{Code: "8249", Description: "Escuelas vocacionales y tecnicas", Category: "Educacion", Networks: all, RiskLevel: "low"},
	{Code: "8299", Description: "Servicios educativos no clasificados", Category: "Educacion", Networks: all, RiskLevel: "low"},

	// ── Gobierno / Government ────────────────────────────────────────
	{Code: "9211", Description: "Multas y sanciones legales", Category: "Gobierno", Networks: all, RiskLevel: "low"},
	{Code: "9222", Description: "Multas", Category: "Gobierno", Networks: all, RiskLevel: "low"},
	{Code: "9311", Description: "Pagos de impuestos", Category: "Gobierno", Networks: all, RiskLevel: "low"},
	{Code: "9399", Description: "Servicios gubernamentales no clasificados", Category: "Gobierno", Networks: all, RiskLevel: "low"},
	{Code: "9402", Description: "Servicios postales gubernamentales", Category: "Gobierno", Networks: all, RiskLevel: "low"},
	{Code: "9405", Description: "Embajadas y consulados (US)", Category: "Gobierno", Networks: all, RiskLevel: "low"},

	// ── Organizaciones / Non-Profit ──────────────────────────────────
	{Code: "8398", Description: "Organizaciones caritativas y sociales", Category: "Organizaciones", Networks: all, RiskLevel: "medium"},
	{Code: "8641", Description: "Asociaciones civicas, sociales, fraternales", Category: "Organizaciones", Networks: all, RiskLevel: "low"},
	{Code: "8651", Description: "Organizaciones politicas", Category: "Organizaciones", Networks: all, RiskLevel: "medium"},
	{Code: "8661", Description: "Organizaciones religiosas", Category: "Organizaciones", Networks: all, RiskLevel: "medium"},
	{Code: "8675", Description: "Asociaciones de automoviles (AAA)", Category: "Organizaciones", Networks: all, RiskLevel: "low"},
	{Code: "8699", Description: "Organizaciones de membresía no clasificadas", Category: "Organizaciones", Networks: all, RiskLevel: "medium"},

	// ── Ropa y Moda / Apparel ────────────────────────────────────────
	{Code: "5611", Description: "Tiendas de ropa para hombre", Category: "Ropa y Moda", Networks: all, RiskLevel: "low"},
	{Code: "5621", Description: "Tiendas de ropa para mujer", Category: "Ropa y Moda", Networks: all, RiskLevel: "low"},
	{Code: "5631", Description: "Accesorios para mujer", Category: "Ropa y Moda", Networks: all, RiskLevel: "low"},
	{Code: "5641", Description: "Tiendas de ropa para ninos", Category: "Ropa y Moda", Networks: all, RiskLevel: "low"},
	{Code: "5651", Description: "Tiendas de ropa familiar", Category: "Ropa y Moda", Networks: all, RiskLevel: "low"},
	{Code: "5661", Description: "Zapaterias", Category: "Ropa y Moda", Networks: all, RiskLevel: "low"},
	{Code: "5691", Description: "Tiendas de ropa (mixtas)", Category: "Ropa y Moda", Networks: all, RiskLevel: "low"},
	{Code: "5699", Description: "Accesorios de vestir miscelaneos", Category: "Ropa y Moda", Networks: all, RiskLevel: "low"},

	// ── Servicios de Entretenimiento / Entertainment ──────────────────
	{Code: "7832", Description: "Cines y salas de cine", Category: "Entretenimiento", Networks: all, RiskLevel: "low"},
	{Code: "7841", Description: "Renta de videos / DVD / streaming", Category: "Entretenimiento", Networks: all, RiskLevel: "low"},
	{Code: "7911", Description: "Salones de baile y estudio de danza", Category: "Entretenimiento", Networks: all, RiskLevel: "low"},
	{Code: "7922", Description: "Venta de boletos para espectaculos", Category: "Entretenimiento", Networks: all, RiskLevel: "low"},
	{Code: "7929", Description: "Bandas, orquestas, espectaculos", Category: "Entretenimiento", Networks: all, RiskLevel: "low"},
	{Code: "7932", Description: "Salones de billar y pool", Category: "Entretenimiento", Networks: all, RiskLevel: "low"},
	{Code: "7933", Description: "Boleras", Category: "Entretenimiento", Networks: all, RiskLevel: "low"},
	{Code: "7941", Description: "Clubes deportivos y eventos atleticos", Category: "Entretenimiento", Networks: all, RiskLevel: "low"},
	{Code: "7991", Description: "Atracciones turisticas y exhibiciones", Category: "Entretenimiento", Networks: all, RiskLevel: "low"},
	{Code: "7992", Description: "Campos de golf publicos", Category: "Entretenimiento", Networks: all, RiskLevel: "low"},
	{Code: "7994", Description: "Videojuegos arcade", Category: "Entretenimiento", Networks: all, RiskLevel: "low"},
	{Code: "7996", Description: "Parques de diversiones y circos", Category: "Entretenimiento", Networks: all, RiskLevel: "low"},
	{Code: "7997", Description: "Clubes deportivos, gimnasios", Category: "Entretenimiento", Networks: all, RiskLevel: "low"},
	{Code: "7998", Description: "Acuarios, parques acuaticos", Category: "Entretenimiento", Networks: all, RiskLevel: "low"},
	{Code: "7999", Description: "Recreacion no clasificada", Category: "Entretenimiento", Networks: all, RiskLevel: "low"},

	// ── Contenido Digital y Alto Riesgo / Digital High Risk ───────────
	{Code: "5962", Description: "Ventas directas / telemercadeo (alto riesgo)", Category: "Alto Riesgo Digital", Networks: all, RiskLevel: "high"},
	{Code: "5963", Description: "Door-to-door sales / ventas puerta a puerta", Category: "Alto Riesgo Digital", Networks: all, RiskLevel: "high"},
	{Code: "5967", Description: "Marketing directo - telemarketing inbound", Category: "Alto Riesgo Digital", Networks: all, RiskLevel: "high"},
	{Code: "7273", Description: "Servicios de citas y acompanantes", Category: "Alto Riesgo Digital", Networks: all, RiskLevel: "high"},
	{Code: "7297", Description: "Clubes de salud y spa", Category: "Alto Riesgo Digital", Networks: all, RiskLevel: "medium"},

	// ── Otros / Miscellaneous ────────────────────────────────────────
	{Code: "5131", Description: "Textiles y piezas de tela al por mayor", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5137", Description: "Uniformes y ropa de trabajo", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5169", Description: "Quimicos y productos afines", Category: "Otros", Networks: all, RiskLevel: "medium"},
	{Code: "5172", Description: "Productos de petroleo al por mayor", Category: "Otros", Networks: all, RiskLevel: "medium"},
	{Code: "5192", Description: "Libros, periodicos, revistas al por mayor", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5193", Description: "Flores y suministros de floreria", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5200", Description: "Ferreteria y materiales de construccion", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5211", Description: "Materiales de construccion y madera", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5231", Description: "Pintura, vidrio y papel tapiz", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5251", Description: "Ferreterias", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5261", Description: "Jardineria y viveros", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5271", Description: "Casas moviles", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5310", Description: "Tiendas de descuento", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5511", Description: "Distribuidores de autos y camiones", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5521", Description: "Autos usados", Category: "Otros", Networks: all, RiskLevel: "medium"},
	{Code: "5531", Description: "Tiendas de autopartes y accesorios", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5532", Description: "Tiendas de llantas", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5533", Description: "Tiendas de refacciones automotrices", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5571", Description: "Distribuidores de motocicletas", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5592", Description: "Casas rodantes y trailers", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5598", Description: "Distribuidores de motonieve", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5712", Description: "Muebles y decoracion del hogar", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5713", Description: "Alfombras y pisos", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5714", Description: "Cortinas y tapiceria", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5718", Description: "Chimeneas y accesorios", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5719", Description: "Accesorios del hogar miscelaneos", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5722", Description: "Electrodomesticos del hogar", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5733", Description: "Tiendas de instrumentos musicales", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5921", Description: "Licorerías y vinos", Category: "Otros", Networks: all, RiskLevel: "medium"},
	{Code: "5931", Description: "Tiendas de segunda mano / usados", Category: "Otros", Networks: all, RiskLevel: "medium"},
	{Code: "5932", Description: "Tiendas de antigüedades", Category: "Otros", Networks: all, RiskLevel: "medium"},
	{Code: "5941", Description: "Tiendas de articulos deportivos", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5942", Description: "Librerias", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5943", Description: "Papelerias y oficina", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5945", Description: "Jugueterias", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5946", Description: "Tiendas de fotografia", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5947", Description: "Regalos, tarjetas y recuerdos", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5948", Description: "Tiendas de equipaje y piel", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5949", Description: "Tiendas de costura y telas", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5950", Description: "Cristaleria y vidrieria", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5970", Description: "Tiendas de arte y galeries", Category: "Otros", Networks: all, RiskLevel: "medium"},
	{Code: "5971", Description: "Galeries y distribuidores de arte", Category: "Otros", Networks: all, RiskLevel: "medium"},
	{Code: "5972", Description: "Numismatica (monedas) y filatelia (estampillas)", Category: "Otros", Networks: all, RiskLevel: "high"},
	{Code: "5973", Description: "Tiendas de articulos religiosos", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5975", Description: "Audifonos para sordera", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5976", Description: "Aparatos ortopedicos", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5977", Description: "Cosmeticos", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5978", Description: "Maquinas de escribir y materiales de oficina", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5983", Description: "Combustible y lena", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5992", Description: "Floristerias", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5993", Description: "Cigarros y tabacos", Category: "Otros", Networks: all, RiskLevel: "medium"},
	{Code: "5994", Description: "Periodicos y revistas", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5995", Description: "Mascotas y alimento para mascotas", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5996", Description: "Piscinas y albercas", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5997", Description: "Navajas y cuchillos", Category: "Otros", Networks: all, RiskLevel: "medium"},
	{Code: "5998", Description: "Tiendas de carpas y toldos", Category: "Otros", Networks: all, RiskLevel: "low"},
	{Code: "5999", Description: "Tiendas miscelaneas y especializadas", Category: "Otros", Networks: all, RiskLevel: "low"},

	// ── Servicios Varios / Misc Services ─────────────────────────────
	{Code: "7210", Description: "Lavanderia, limpieza y prendas", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7211", Description: "Tintorerias", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7216", Description: "Lavanderia industrial", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7217", Description: "Limpieza de alfombras", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7221", Description: "Estudios fotograficos y retratos", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7230", Description: "Salones de belleza", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7251", Description: "Reparacion de calzado y sombreros", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7261", Description: "Funerarias y servicios funerarios", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7276", Description: "Preparacion de impuestos", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7278", Description: "Suscripcion a revistas / clubes de compras", Category: "Servicios Varios", Networks: all, RiskLevel: "medium"},
	{Code: "7298", Description: "Spas y salones de masaje", Category: "Servicios Varios", Networks: all, RiskLevel: "medium"},
	{Code: "7311", Description: "Publicidad", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7321", Description: "Agencias de cobranza", Category: "Servicios Varios", Networks: all, RiskLevel: "medium"},
	{Code: "7333", Description: "Servicios de impresion y fotografia comercial", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7338", Description: "Fotocopiado y reproduccion", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7339", Description: "Servicios de secretaria y estenografia", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7342", Description: "Exterminacion y desinfeccion", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7349", Description: "Servicios de limpieza y mantenimiento", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7361", Description: "Agencias de empleo y colocacion", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7372", Description: "Programacion y software", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7375", Description: "Servicios de informacion y datos", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7379", Description: "Mantenimiento de computadoras", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7394", Description: "Renta de equipo y maquinaria", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7395", Description: "Revelado de fotos", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7399", Description: "Servicios comerciales no clasificados", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7531", Description: "Taller de carroceria automotriz", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7534", Description: "Reparacion de llantas", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7535", Description: "Pintura automotriz", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7538", Description: "Talleres mecanicos automotrices", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7542", Description: "Autolavados", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7549", Description: "Servicio de grua y remolque", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7622", Description: "Reparacion de electronica", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7623", Description: "Reparacion de aire acondicionado", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7629", Description: "Reparacion de electrodomesticos menores", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7631", Description: "Reparacion de relojes y joyeria", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7641", Description: "Retapizado de muebles", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7692", Description: "Soldadura", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},
	{Code: "7699", Description: "Talleres de reparacion miscelaneos", Category: "Servicios Varios", Networks: all, RiskLevel: "low"},

	// ── Construccion / Construction ───────────────────────────────────
	{Code: "1520", Description: "Contratistas generales - residencial", Category: "Construccion", Networks: all, RiskLevel: "low"},
	{Code: "1711", Description: "Contratistas de plomeria y calefaccion", Category: "Construccion", Networks: all, RiskLevel: "low"},
	{Code: "1731", Description: "Contratistas electricos", Category: "Construccion", Networks: all, RiskLevel: "low"},
	{Code: "1740", Description: "Contratistas de albañileria y concreto", Category: "Construccion", Networks: all, RiskLevel: "low"},
	{Code: "1750", Description: "Contratistas de carpinteria", Category: "Construccion", Networks: all, RiskLevel: "low"},
	{Code: "1761", Description: "Contratistas de techos y laminas", Category: "Construccion", Networks: all, RiskLevel: "low"},
	{Code: "1771", Description: "Contratistas de concreto", Category: "Construccion", Networks: all, RiskLevel: "low"},
	{Code: "1799", Description: "Contratistas especializados no clasificados", Category: "Construccion", Networks: all, RiskLevel: "low"},

	// ── Correo y Envios / Mail & Shipping ─────────────────────────────
	{Code: "4215", Description: "Servicios de mensajeria (DHL, FedEx, UPS)", Category: "Correo y Envios", Networks: all, RiskLevel: "low"},
	{Code: "4225", Description: "Almacenamiento publico y bodegas", Category: "Correo y Envios", Networks: all, RiskLevel: "low"},
	{Code: "5021", Description: "Muebles de oficina al por mayor", Category: "Correo y Envios", Networks: all, RiskLevel: "low"},
}
